# Made with love
#
# This is the configuration file for the labeler action
# for more example in setting this file or informations about
# the labeler action, see:
# https://github.com/actions/labeler
#
# If you want to use it in your project, you will simply need:
# 1 - commit this config file to your repository into the '.github' folder.
# 2 - commit the 'labeler.yml' action file into the '.github/workflows' folder.
#
# You will probably need to modify the labels, or their targets.
#


# Add 'Github' label to any git file changes within the source dir
Github:
- .github/**/*

# Add 'Automation' label to any file changes within scripts or workflows dir
Automation:
- .github/scripts/**/*
- .github/workflows/**/*

# Add 'Core' label to any change within the 'core' package
Core:
- app/src/main/java/**/*

# Add 'Fastlane' label to any change within the 'play' folder and subfolder(s)
Fastlane:
- fastlane/**/*

# Add 'Gradle wrapper' label to any change within the 'gradle' folder and subfolder
Gradle wrapper:
- gradle/wrapper/**/*

# Add 'Translation` label to any change to strings.xml files as long as the English strings.xml file hasn't changed
Translation:
- any: ['app/src/**/strings.xml']
  all: ['!app/src/main/res/values/strings.xml']

